### ISSUE TITLE
Warning: Calling depends_on :macos => :yosemite is deprecated! There is no replacement.

### ISSUE THREAD

**Issue by luowencai** [majd/homebrew-repo#1]
Warning: Calling depends_on :macos => :yosemite is deprecated! There is no replacement.
Please report this issue to the majd/repo tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/majd/homebrew-repo/Formula/class-dump.rb:10

**Comment by majd** [comment]
Fixed in [35bd93f](https://github.com/majd/homebrew-repo/commit/35bd93fc6a20a1991d1e9d147e274c4680a81de6).
